const ERROR_FILE_PROSESSING = -1001;
const ERROR_GETTING_CHAT_RESPONSE = -1002;
const ALL_DONE = 1003;
const FILE_GENERATING = 1004;
const PROCESSING_FILE = 1005;
module.exports = {
  ERROR_FILE_PROSESSING,
  ERROR_GETTING_CHAT_RESPONSE,
  ALL_DONE,
  FILE_GENERATING,
  PROCESSING_FILE,
};
